FROM php:8.3-fpm

WORKDIR /var/www


RUN apt-get update && apt-get install -y \
      apt-utils \
      libicu-dev \
      libonig-dev \
      libpq-dev \
      libpng-dev \
      libzip-dev \
      zip unzip \
      git && \
      docker-php-ext-configure intl && \
      docker-php-ext-install intl && \
      docker-php-ext-install mbstring && \
      docker-php-ext-install pdo_mysql && \
      docker-php-ext-install bcmath && \
      docker-php-ext-install gd && \
      docker-php-ext-install zip && \
      apt-get clean && \
      rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN docker-php-ext-enable intl mbstring

RUN apt-get update && apt-get install -y nodejs
RUN apt-get update && apt-get install -y npm

COPY ./php.ini /usr/local/etc/php/conf.d/php.ini



ENV COMPOSER_ALLOW_SUPERUSER=1
RUN curl -sS https://getcomposer.org/installer | php -- \
    --filename=composer \
    --install-dir=/usr/local/bin